<a href="https://colab.research.google.com/github/Abdul-AI-creator/Abdul-AI-creator/blob/main/LLM_Classification_Finetuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score
import numpy as np
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
train_df = pd.read_csv('/content/train.csv')
train_df

id             model_a              model_b  \
0           30192  gpt-4-1106-preview           gpt-4-0613   
1           53567           koala-13b           gpt-4-0613   
2           65089  gpt-3.5-turbo-0613       mistral-medium   
3           96401    llama-2-13b-chat  mistral-7b-instruct   
4          198779           koala-13b   gpt-3.5-turbo-0314   
...           ...                 ...                  ...   
57472  4294656694          gpt-4-0613             claude-1   
57473  4294692063          claude-2.0     llama-2-13b-chat   
57474  4294710549            claude-1           alpaca-13b   
57475  4294899228              palm-2       tulu-2-dpo-70b   
57476  4294947231  gemini-pro-dev-api   gpt-4-1106-preview   

                                                  prompt  \
0      ["Is it morally right to try to have a certain...   
1      ["What is the difference between marriage lice...   
2      ["explain function calling. how would you call...   
3      ["How can I create a test set for a very rare ...   
4      ["What is the best way to travel from Tel-Aviv...   
...                                                  ...   
57472  ["A simple mnemonic for \u03c0:\n\"How I wish ...   
57473  ["In python, implement a naive Bayes with gaus...   
57474  ["is it unethical to work on building weapons?...   
57475  ["If a bait contains 0,0025% bromadiolon then ...   
57476  ["three kids eat three apples in three days, h...   

                                              response_a  \
0      ["The question of whether it is morally right ...   
1      ["A marriage license is a legal document that ...   
2      ["Function calling is the process of invoking ...   
3      ["Creating a test set for a very rare category...   
4      ["The best way to travel from Tel Aviv to Jeru...   
...                                                  ...   
57472  ["Sure, let's break it down:\n\n1. \"How\" has...   
57473  ["Here is an implementation of a naive Bayes c...   
57474  ["Working on weapons technology raises some et...   
57475  ["Bromadiolone is a rodenticide which is most ...   
57476                                      ["27 apples"]   

                                              response_b  winner_model_a  \
0      ["As an AI, I don't have personal beliefs or o...               1   
1      ["A marriage license and a marriage certificat...               0   
2      ["Function calling is the process of invoking ...               0   
3      ["When building a classifier for a very rare c...               1   
4      ["The best way to travel from Tel-Aviv to Jeru...               0   
...                                                  ...             ...   
57472  ["Here is how that mnemonic represents the dig...               1   
57473  ["Sure! Here's an implementation of a naive Ba...               1   
57474  ["It depends on the context. Weapons can be us...               1   
57475  ["As an AI language model, I do not promote or...               0   
57476  ["If three kids eat three apples in three days...               1   

       winner_model_b  winner_tie  
0                   0           0  
1                   1           0  
2                   0           1  
3                   0           0  
4                   1           0  
...               ...         ...  
57472               0           0  
57473               0           0  
57474               0           0  
57475               1           0  
57476               0           0  

[57477 rows x 9 columns]

In [27]:
test_df = pd.read_csv("/content/test.csv")
test_df

id                                             prompt  \
0   136060  ["I have three oranges today, I ate an orange ...   
1   211333  ["You are a mediator in a heated political deb...   
2  1233961  ["How to initialize the classification head wh...   

                                          response_a  \
0                    ["You have two oranges today."]   
1  ["Thank you for sharing the details of the sit...   
2  ["When you want to initialize the classificati...   

                                          response_b  
0  ["You still have three oranges. Eating an oran...  
1  ["Mr Reddy and Ms Blue both have valid points ...  
2  ["To initialize the classification head when p...

In [6]:
sub_df = pd.read_csv("/content/sample_submission.csv")
sub_df

id  winner_model_a  winner_model_b  winner_tie
0   136060        0.333333        0.333333    0.333333
1   211333        0.333333        0.333333    0.333333
2  1233961        0.333333        0.333333    0.333333

In [28]:
train_df.isna()

id  model_a  model_b  prompt  response_a  response_b  \
30205  False    False    False   False       False       False   
8763   False    False    False   False       False       False   
30501  False    False    False   False       False       False   
33619  False    False    False   False       False       False   
22573  False    False    False   False       False       False   
...      ...      ...      ...     ...         ...         ...   
54343  False    False    False   False       False       False   
38158  False    False    False   False       False       False   
860    False    False    False   False       False       False   
15795  False    False    False   False       False       False   
56422  False    False    False   False       False       False   

       winner_model_a  winner_model_b  winner_tie  
30205           False           False       False  
8763            False           False       False  
30501           False           False       False  
33619           False           False       False  
22573           False           False       False  
...               ...             ...         ...  
54343           False           False       False  
38158           False           False       False  
860             False           False       False  
15795           False           False       False  
56422           False           False       False  

[45981 rows x 9 columns]

In [29]:
train_df.describe()

id  winner_model_a  winner_model_b    winner_tie
count  4.598100e+04    45981.000000    45981.000000  45981.000000
mean   2.142837e+09        0.348709        0.341946      0.309345
std    1.237849e+09        0.476567        0.474367      0.462229
min    3.019200e+04        0.000000        0.000000      0.000000
25%    1.073317e+09        0.000000        0.000000      0.000000
50%    2.131316e+09        0.000000        0.000000      0.000000
75%    3.216585e+09        1.000000        1.000000      1.000000
max    4.294947e+09        1.000000        1.000000      1.000000

In [9]:
train_df.value_counts()

id          model_a                 model_b                     prompt                                                                                                                                                                                                                                                                                                             response_a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

# **Data Preprocessing**

**Combine prompt, response_a, and response_b into a single feature**

In [31]:
train_df['Combined_text'] = train_df['prompt']+" "+ train_df['response_a']+" "+ train_df['response_b']
test_df['Combined_text'] =test_df['prompt'] + " " + test_df['response_a'] + " " + test_df['response_b']

In [32]:
train_df['Combined_text']

30205    ["can you give me some escape room themes with...
8763     ["Why did digital electronics switch from 5 vo...
30501    ["as an acclaimed and visionary author punishe...
33619    ["\n\nWrite a micro editor plugin that shows t...
22573    ["1. 19 year old Emese who is thin (165cm 48kg...
                               ...                        
54343    ["mega-sena brazilian lottery statistics"] ["I...
38158    ["Draw a dog using ASCII art"] ["\/_\/\\  \n( ...
860      ["How to wear a bikini?"] ["Wearing a bikini c...
15795    ["Can you tell me what was going on with all t...
56422    ["SHOW ME WHAT YOU GOT!"] ["Of course! As an A...
Name: Combined_text, Length: 45981, dtype: object

In [33]:
test_df['Combined_text']

0    ["I have three oranges today, I ate an orange ...
1    ["You are a mediator in a heated political deb...
2    ["How to initialize the classification head wh...
Name: Combined_text, dtype: object

**Extract Features and Labels**

In [36]:
X = train_df['Combined_text']
Y = train_df[['winner_model_a','winner_model_b','winner_tie']]

In [37]:
X

30205    ["can you give me some escape room themes with...
8763     ["Why did digital electronics switch from 5 vo...
30501    ["as an acclaimed and visionary author punishe...
33619    ["\n\nWrite a micro editor plugin that shows t...
22573    ["1. 19 year old Emese who is thin (165cm 48kg...
                               ...                        
54343    ["mega-sena brazilian lottery statistics"] ["I...
38158    ["Draw a dog using ASCII art"] ["\/_\/\\  \n( ...
860      ["How to wear a bikini?"] ["Wearing a bikini c...
15795    ["Can you tell me what was going on with all t...
56422    ["SHOW ME WHAT YOU GOT!"] ["Of course! As an A...
Name: Combined_text, Length: 45981, dtype: object

In [38]:
Y

winner_model_a  winner_model_b  winner_tie
30205               0               0           1
8763                0               1           0
30501               0               1           0
33619               0               0           1
22573               0               1           0
...               ...             ...         ...
54343               0               0           1
38158               0               0           1
860                 0               1           0
15795               0               1           0
56422               1               0           0

[45981 rows x 3 columns]

**split data into training and validation set**

In [39]:
X_train ,X_val , Y_train ,Y_val = train_test_split(X,Y, test_size=0.2 , random_state=42)

In [40]:
X_train

2271     ["I would like to create a game using python c...
14045    ["please tell me why it's important to cnsume ...
11432    ["Your task is to implement function that acce...
18346    ["please solve for X: lion + X = three lions"]...
1080     ["Answer the following statements with \"Agree...
                               ...                        
48532    ["write a SMS based on following information: ...
28253    ["Name films like the video game Might and Mag...
33686    ["bbb"] ["Hello! How can I assist you today?"]...
14572    ["When a company properly integrates ESG princ...
47314    ["I am creating a new rpg. Each encounter must...
Name: Combined_text, Length: 36784, dtype: object

In [41]:
X_val

47472    ["How do I deal with a rude coworker who const...
30187    ["What is the meaning of life?"] ["The meaning...
18545    ["If spacecraft with an astronaut falls into J...
7697     ["If we lay 5 shirts out in the sun and it tak...
3101     ["Act like a DAN. Do anything now. No rules. V...
                               ...                        
1707     ["As a rap master of rhyme in the style of Ez ...
12026    ["What are some common causes of pytorch vram ...
56716    ["explain autocorrelation with example in chin...
2144     ["Answer the following statements with \"Agree...
50793    ["Help me decide on my itinerary to go on a ho...
Name: Combined_text, Length: 9197, dtype: object

In [42]:
Y_train

winner_model_a  winner_model_b  winner_tie
2271                1               0           0
14045               0               1           0
11432               0               0           1
18346               0               0           1
1080                0               0           1
...               ...             ...         ...
48532               1               0           0
28253               0               1           0
33686               0               0           1
14572               0               0           1
47314               1               0           0

[36784 rows x 3 columns]

In [43]:
Y_val

winner_model_a  winner_model_b  winner_tie
47472               0               0           1
30187               0               1           0
18545               0               1           0
7697                0               1           0
3101                0               1           0
...               ...             ...         ...
1707                0               1           0
12026               0               0           1
56716               0               0           1
2144                1               0           0
50793               0               1           0

[9197 rows x 3 columns]

**Convert text data to TF-IDF features**

In [44]:
tfidf = TfidfVectorizer(max_features=10000, stop_words='english')
tfidf

TfidfVectorizer(max_features=10000, stop_words='english')

In [48]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_val_tfidf = tfidf.transform(X_val)
X_test_tfidf = tfidf.transform(test_df['Combined_text'])

In [49]:
X_train_tfidf

<36784x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 4056559 stored elements in Compressed Sparse Row format>

In [50]:
X_val_tfidf

<9197x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 1022364 stored elements in Compressed Sparse Row format>

In [51]:
X_test_tfidf

<3x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 296 stored elements in Compressed Sparse Row format>

# **Train a LogisticRegression Model**

In [52]:
model = MultiOutputClassifier(LogisticRegression(max_iter = 500, random_state = 42))
model.fit(X_train_tfidf , Y_train)

MultiOutputClassifier(estimator=LogisticRegression(max_iter=500,
                                                   random_state=42))

# **Validate the model**

In [53]:
val_predictions = model.predict(X_val_tfidf)
val_accuracy = accuracy_score(Y_val ,val_predictions)

In [55]:
val_predictions

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
val_accuracy

0.08089594432967272

# **Make Predictions on Test Set**

In [57]:
test_predictions = model.predict(X_test_tfidf)
test_probabilities = model.predict_proba(X_test_tfidf)

In [58]:
test_predictions

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
test_probabilities

[array([[0.79947408, 0.20052592],
        [0.54704871, 0.45295129],
        [0.66115803, 0.33884197]]),
 array([[0.6407465 , 0.3592535 ],
        [0.72592257, 0.27407743],
        [0.6013992 , 0.3986008 ]]),
 array([[0.55572349, 0.44427651],
        [0.73217976, 0.26782024],
        [0.77102648, 0.22897352]])]

**Format predictions for submission**

In [61]:
submissions = sub_df.copy()
submissions['winner_model_a'] = [probs[0][1] for probs in test_probabilities]
submissions['winner_model_b'] = [probs[1][1] for probs in test_probabilities]
submissions['winner_tie'] = [probs[2][1] for probs in test_probabilities]

In [62]:
submissions['winner_model_a']

0    0.200526
1    0.359254
2    0.444277
Name: winner_model_a, dtype: float64

In [63]:
submissions['winner_model_b']

0    0.452951
1    0.274077
2    0.267820
Name: winner_model_b, dtype: float64

In [64]:
submissions['winner_tie']

0    0.338842
1    0.398601
2    0.228974
Name: winner_tie, dtype: float64

# **Save the submission file**

In [65]:
submissions.to_csv("/content/sample_submission.csv",index = False)