<a href="https://colab.research.google.com/github/Abdul-AI-creator/Abdul-AI-creator/blob/main/Pytorch_Basic_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision
import torch.nn as nn
import torchvision.transforms as transforms
import numpy as np

# Basic autograd example 1

In [2]:
# Create Tensor
x = torch.tensor(1. ,requires_grad=True)
w = torch.tensor(2. ,requires_grad=True)
b = torch.tensor(3. ,requires_grad=True)

In [3]:
# computational Graph
y = w * x + b
y

tensor(5., grad_fn=<AddBackward0>)

In [4]:
y.backward()

In [5]:
# print Gradients
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


**Basic autograd example 2**

In [6]:
x=torch.rand(10, 3)
y =torch.randn(10, 2)

In [7]:
x

tensor([[0.1264, 0.9934, 0.7934],
        [0.9520, 0.1711, 0.4189],
        [0.0529, 0.3872, 0.8397],
        [0.4842, 0.2677, 0.4434],
        [0.3410, 0.8585, 0.6895],
        [0.8638, 0.7206, 0.9231],
        [0.5750, 0.3488, 0.3496],
        [0.7300, 0.4347, 0.5083],
        [0.9405, 0.0491, 0.3077],
        [0.4858, 0.0297, 0.4563]])

In [8]:
y

tensor([[-0.6259,  0.5312],
        [ 0.1523,  1.5146],
        [-0.9905, -0.1823],
        [-0.5362,  2.0518],
        [ 0.0953, -0.1191],
        [-2.1011, -1.7400],
        [-0.5224, -0.8912],
        [-3.7888, -0.5088],
        [-0.3574, -0.7572],
        [-0.9674, -0.3828]])

**build fully Connected Layer**

In [9]:
linear = nn.Linear(3 ,2)
print('w: ',linear.weight)
print('b: ',linear.bias)

w:  Parameter containing:
tensor([[-0.2798,  0.5682,  0.4313],
        [ 0.4809, -0.5478, -0.5766]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2170, -0.5056], requires_grad=True)


In [10]:
criterion =nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters() ,lr=0.001)

In [11]:
# Forward pass
pred = linear(x)
pred

tensor([[ 0.6543, -1.4465],
        [-0.2055, -0.3831],
        [ 0.3504, -1.1765],
        [-0.0091, -0.6751],
        [ 0.4728, -1.2095],
        [ 0.3489, -1.0172],
        [-0.0289, -0.6217],
        [ 0.0450, -0.6858],
        [-0.3195, -0.2576],
        [-0.1392, -0.5514]], grad_fn=<AddmmBackward0>)

In [12]:
# compute loss
loss =criterion(pred ,y)
print('loss: ',loss.item())

loss:  2.1823105812072754


In [13]:
# Backward Pass
loss.backward()

In [14]:
print('dL/dw' ,linear.weight.grad)
print('dL/db' ,linear.bias.grad)

dL/dw tensor([[ 0.5913,  0.5826,  0.7258],
        [-0.2763, -0.3783, -0.4412]])
dL/db tensor([ 1.0811, -0.7540])


In [15]:
# Step Gradient
optimizer.step()

In [16]:
# You can also perform gradient descent at the low level.
linear.weight.data.sub_(0.01 * linear.weight.grad.data)
linear.bias.data.sub_(0.01 * linear.bias.grad.data)

tensor([-0.2289, -0.4973])

In [17]:
# Print out the loss after 1-step gradient descent.
pred= linear(x)
loss = criterion(pred, y)
print('Loss after one Step Optimization',loss.item())

Loss after one Step Optimization 2.145641803741455


# Loading data from numpy

In [18]:
x=np.array([[1,2] ,[3,4]])
y=torch.from_numpy(x)
z = y.numpy()

**Input PipeLine**

`Download and convert Cifar-10 Dataset`

In [19]:
train_ds = torchvision.datasets.CIFAR10(root = '../../data/',train =True ,transform=transforms.ToTensor(),download=True)
train_ds

100%|██████████| 170M/170M [00:04<00:00, 39.9MB/s]


Extracting ../../data/cifar-10-python.tar.gz to ../../data/


Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ../../data/
    Split: Train
    StandardTransform
Transform: ToTensor()

In [21]:
# Fetch one data pair (Read data from disk)
images ,labels =train_ds[0]
print(images.size())
print(labels)
images

torch.Size([3, 32, 32])
6


tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
         [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
         [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
         ...,
         [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
         [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
         [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

        [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
         [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
         [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
         ...,
         [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
         [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
         [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

        [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
         [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
         [0.0824, 0.0000, 0.0314,  ..., 0.1961, 0.1961, 0.

**Train Data Loader** `provides queues and threads in a very simple way)`

In [25]:
train_dl =torch.utils.data.DataLoader(dataset =train_ds ,batch_size = 64 ,shuffle=True)
train_dl

When iteration starts Que and thread starts to load data from  Files

In [27]:
data_iter = iter(train_dl)
# mini batch images and labels
images, labels = next(data_iter)

**USAGE OF DATALOADERA**

In [28]:
for images ,labels in train_dl:
  pass

**Input pipeline for custom dataset**

In [34]:
class CustomerDataset(torch.utils.data.Dataset):
  def __init__(self,data,labels):
    self.data =data
    self.labels =labels
    # Todo
    # initialize filepath or list of file name

  def __len__(self):

    # change 0 to total size of dataset
    return len(self.data)

  def __getitem__(self ,index):

    # todo
    # Read one data from file (e.g. use numpy.fromfile , PIL.Image.open)
    # Preproces data (e.g torchvision.Transform)
    # return Data pair(images and labels)
    return self.data[index] ,self.labels[index]


In [35]:
data = torch.randn(100,10)
labels = torch.randint(0,2, (100,))
custom_ds =CustomerDataset(data , labels)

In [36]:
len(custom_ds)

100

use the prebuilt data loader

In [38]:

train_dl =torch.utils.data.DataLoader(dataset=custom_ds ,batch_size = 64 ,shuffle=True)
train_dl

Download and load the pretrained ResNet-18.

In [39]:
resnet =torchvision.models.resnet18(pretrained=True)
resnet

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 162MB/s]


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

to finetune only the top layer of the model

In [40]:
for param in resnet.parameters():
  param.requires_grad=False
  # Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features ,100)

images =torch.randn(64,3,224,224)
output = resnet(images)
print(output.size())

torch.Size([64, 100])


In [41]:
torch.save(resnet.state_dict(),'model_resnet.csv')

In [42]:
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

<ipython-input-42-c2ed98f4147d>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  resnet.load_state_dict(torch.load('params.ckpt'))


<All keys matched successfully>