<a href="https://colab.research.google.com/github/Abdul-AI-creator/Abdul-AI-creator/blob/main/Pytorch_(Basics_%26_Gradient_Descent_%2CTensors%2C_Autograd_%26_Linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Basics: Tensors & Gradients

In [8]:
import torch

In [9]:
t1=torch.tensor(4.)
print(t1)
print(t1.shape)
t1.dtype


tensor(4.)
torch.Size([])


torch.float32

In [10]:
# vector
t2=torch.tensor([1,2,3,4,5.])
print(t2)
print(t2.shape)
t2.dtype

tensor([1., 2., 3., 4., 5.])
torch.Size([5])


torch.float32

In [11]:
# Matrix
t3 =torch.tensor([
    [3,4],
    [4,6],
    [7,8]
])
print(t3)
print(t3.shape)
t3.dtype

tensor([[3, 4],
        [4, 6],
        [7, 8]])
torch.Size([3, 2])


torch.int64

In [12]:
# 3-dimensional Array
t4 = torch.tensor([
    [[1,2,4,5],
    [0,9,8,7]],
    [[12,13,14,15],
     [10,20,30,40]]
])
print(t4)
print(t4.shape)
t4.dtype

tensor([[[ 1,  2,  4,  5],
         [ 0,  9,  8,  7]],

        [[12, 13, 14, 15],
         [10, 20, 30, 40]]])
torch.Size([2, 2, 4])


torch.int64

# Tensors operations and Gradients
we can combine tensors with usual arithmetric operations

In [13]:
# Create Tensors
x = torch.tensor(3.)
w = torch.tensor(4. , requires_grad=True)
b = torch.tensor(5. , requires_grad=True)
x ,w ,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [14]:
# Arithmetic Operations
y = w * x +b
y

tensor(17., grad_fn=<AddBackward0>)

In [15]:
# Compute Derivatives
y.backward()

Derivatives or `y` w.r.t to `input tensors` stored in `.grad` property of respective tensor

In [16]:
print("dy/dx: ",x.grad)
print("dy/dw: ",w.grad)
print("dy/db: ",b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


`The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices`

## Interoperability with Numpy

[Numpy](http://www.numpy.org/) is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

* [Matplotlib](https://matplotlib.org/) for plotting and visualization
* [OpenCV](https://opencv.org/) for image and video processing
* [Pandas](https://pandas.pydata.org/) for file I/O and data analysis

Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

In [17]:
import numpy as np
x=np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

`convert numpy array to a torch tensor`

In [18]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [19]:
x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [20]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [21]:
!pip install jovian

In [1]:
import jovian

In [2]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


# Gradient Descent and Linear Regression with PyTorch

## Introduction to Linear Regression

In this tutorial, we'll discuss one of the foundational algorithms in machine learning: *Linear regression*. We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall, and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

Visually, it means that the yield of apples is a linear or planar function of temperature, rainfall and humidity:

![linear-regression-graph](https://i.imgur.com/4DJ9f8X.png)

## Training data
We can represent the training data using two matrices: `inputs` and `targets`, each with one row per observation, and one column per variable.

In [22]:
import numpy as np

In [23]:
# Inputs(Temperature ,Rainfall , Humidity)
inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134 ,58],
    [102,43,37],
    [69,96,70]
],dtype = 'float32')

In [6]:
# Targets (Apple , Oranges)
targets = np.array([
    [56,70],
    [81,101],
    [119,133],
    [22, 37],
    [103,119]
],dtype='float32')

In [24]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression model from scratch
The weights and biases (`w11, w12,... w23, b1 & b2`) can also be represented as matrices, initialized as random values. The first row of `w` and the first element of `b` are used to predict the first target variable, i.e., yield of apples, and similarly, the second for oranges.

In [25]:
# Weights and Biases
w = torch.randn(2, 3 ,requires_grad=True)
b= torch.randn(2 , requires_grad=True)
print(w)
print(b)

tensor([[-1.2183,  0.3783, -0.9838],
        [ 0.6631,  0.7384, -1.1521]], requires_grad=True)
tensor([-1.0861, -0.4510], requires_grad=True)


`torch.randn` creates a tensor with the given shape, with elements picked randomly from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 and standard deviation 1.

Our *model* is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).

![matrix-mult](https://i.imgur.com/WGXLFvA.png)

We can define the model as follows:

In [26]:
def model(x):
  return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of a tensor.

The matrix obtained by passing the input data into the model is a set of predictions for the target variables.

In [28]:
# generate predictions
preds = model(inputs)
preds

tensor([[-106.9765,   47.8875],
        [-141.6207,   51.1349],
        [-113.4423,   89.3609],
        [-145.4834,   56.3102],
        [-117.6948,   35.5400]], grad_fn=<AddBackward0>)

`Let's compare the predictions of our model with the actual targets.`

In [29]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Loss function

Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets using the following method:

* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [30]:
# MSE loss
def mse(t1, t2):
  diff =t1 - t2
  return torch.sum(diff * diff) / diff.numel()

`**torch.sum** returns the sum of all the elements in a tensor. The **.numel **method of a tensor returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.`

In [31]:
# compute loss
loss =mse(preds ,targets)
loss

tensor(21912.5918, grad_fn=<DivBackward0>)

Here’s how we can interpret the result: *On average, each element in the prediction differs from the actual target by the square root of the loss*. And that’s pretty bad, considering the numbers we are trying to predict are themselves in the range 50–200. The result is called the *loss* because it indicates how bad the model is at predicting the target variables. It represents information loss in the model: the lower the loss, the better the model.

## Compute gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases because they have `requires_grad` set to `True`. We'll see how this is useful in just a moment.

In [32]:
loss.backward()

In [33]:
print(w)
print(w.grad)

tensor([[-1.2183,  0.3783, -0.9838],
        [ 0.6631,  0.7384, -1.1521]], requires_grad=True)
tensor([[-16937.8984, -18009.1602, -11276.5771],
        [ -2747.5283,  -3779.8259,  -2360.1992]])


## Adjust weights and biases to reduce the loss

The loss is a [quadratic function](https://en.wikipedia.org/wiki/Quadratic_function) of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. An important insight from calculus is that the gradient indicates the rate of change of the loss, i.e., the loss function's [slope](https://en.wikipedia.org/wiki/Slope) w.r.t. the weights and biases.

If a gradient element is **positive**:

* **increasing** the weight element's value slightly will **increase** the loss
* **decreasing** the weight element's value slightly will **decrease** the loss

![postive-gradient](https://i.imgur.com/WLzJ4xP.png)

If a gradient element is **negative**:

* **increasing** the weight element's value slightly will **decrease** the loss
* **decreasing** the weight element's value slightly will **increase** the loss

![negative=gradient](https://i.imgur.com/dvG2fxU.png)

The increase or decrease in the loss by changing a weight element is proportional to the gradient of the loss w.r.t. that element. This observation forms the basis of _the gradient descent_ optimization algorithm that we'll use to improve our model (by _descending_ along the _gradient_).

We can subtract from each weight element a small quantity proportional to the derivative of the loss w.r.t. that element to reduce the loss slightly.

In [34]:
print(w)
w.grad

tensor([[-1.2183,  0.3783, -0.9838],
        [ 0.6631,  0.7384, -1.1521]], requires_grad=True)


tensor([[-16937.8984, -18009.1602, -11276.5771],
        [ -2747.5283,  -3779.8259,  -2360.1992]])

In [35]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

We multiply the gradients with a very small number (`10^-5` in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the *learning rate* of the algorithm.

We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [36]:
# Let's verify that the loss is actually lower
loss = mse(preds ,targets)
loss

tensor(21912.5918, grad_fn=<DivBackward0>)

Before we proceed, we reset the gradients to zero by invoking the `.zero_()` method. We need to do this because PyTorch accumulates gradients. Otherwise, the next time we invoke `.backward` on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.

In [37]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


## Train the model using gradient descent

As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm. Thus, we can _train_ the model using the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [38]:
preds  =model(inputs)
preds

tensor([[ -77.6948,   53.4409],
        [-103.1401,   58.4723],
        [ -68.0316,   98.1855],
        [-116.2885,   61.6116],
        [ -80.8232,   42.7169]], grad_fn=<AddBackward0>)

In [39]:
loss = mse(preds ,targets)
loss

tensor(14939.7061, grad_fn=<DivBackward0>)

In [40]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-13915.4883, -14763.5088,  -9273.1934],
        [ -2172.1689,  -3156.3838,  -1976.4485]])
tensor([-165.3956,  -29.1146])


In [41]:
# Adjust weights and reset Gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [42]:
print(w)
print(b)

tensor([[-0.9097,  0.7060, -0.7783],
        [ 0.7123,  0.8077, -1.1088]], requires_grad=True)
tensor([-1.0824, -0.4503], requires_grad=True)


**With the new weights and biases, the model should have a lower loss.**

In [43]:
preds = model(inputs)
loss = mse(preds ,targets)
print(loss)

tensor(10239.5137, grad_fn=<DivBackward0>)


## Train for multiple epochs

To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an _epoch_. Let's train the model for 100 epochs.

In [44]:
# train for 100 epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds ,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [45]:
preds = model(inputs)
loss = mse(preds , targets)
print(preds)
print(loss)

tensor([[ 57.0878,  75.5509],
        [ 74.4290,  90.8364],
        [136.5034, 146.8952],
        [ 20.8982,  66.5720],
        [ 88.2845,  84.6932]], grad_fn=<AddBackward0>)
tensor(294.7138, grad_fn=<DivBackward0>)


## Linear regression using PyTorch built-ins

We've implemented linear regression & gradient descent model using some basic tensor operations. However, since this is a common pattern in deep learning, PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.

Let's begin by importing the `torch.nn` package from PyTorch, which contains utility classes for building neural networks.

In [46]:
import torch.nn as nn

In [47]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [48]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [49]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

## Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [50]:
from torch.utils.data import TensorDataset

In [52]:
# Define Dataset
train_ds = TensorDataset(inputs , targets)
train_ds[:5]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

We'll also create a `DataLoader`, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [53]:
from torch.utils.data import DataLoader

In [54]:
# Define data loader
batch_size  = 5
train_dl =DataLoader(train_ds , batch_size,shuffle=True)

In [56]:
for xb , yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 88., 134.,  59.],
        [ 73.,  66.,  44.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  67.,  43.]])
tensor([[118., 132.],
        [ 57.,  69.],
        [ 21.,  38.],
        [104., 118.],
        [ 56.,  70.]])


## nn.Linear

Instead of initializing the weights & biases manually, we can define the model using the `nn.Linear` class from PyTorch, which does it automatically.

In [57]:
# Define Model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1706,  0.4525,  0.3128],
        [ 0.0036, -0.0197,  0.5334]], requires_grad=True)
Parameter containing:
tensor([-0.2105, -0.3341], requires_grad=True)


PyTorch models also have a helpful `.parameters` method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [59]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1706,  0.4525,  0.3128],
         [ 0.0036, -0.0197,  0.5334]], requires_grad=True),
 Parameter containing:
 tensor([-0.2105, -0.3341], requires_grad=True)]

In [60]:
preds = model(inputs)
preds

tensor([[56.0151, 21.5497],
        [75.1580, 32.4039],
        [93.4148, 28.2850],
        [48.2266, 18.9253],
        [76.9007, 35.3680],
        [55.7332, 21.5730],
        [75.0183, 32.9570],
        [93.8982, 28.8220],
        [48.5085, 18.9021],
        [77.0428, 35.8978],
        [55.8754, 22.1028],
        [74.8761, 32.4272],
        [93.5546, 27.7319],
        [48.0845, 18.3955],
        [77.1825, 35.3447]], grad_fn=<AddmmBackward0>)

## Loss Function

Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [62]:
# import nn.functional
import torch.nn.functional as F

The `nn.functional` package contains many useful loss functions and several other utilities.

In [63]:
loss_fn = F.mse_loss
loss_fn

<function torch.nn.functional.mse_loss(input: torch.Tensor, target: torch.Tensor, size_average: Optional[bool] = None, reduce: Optional[bool] = None, reduction: str = 'mean') -> torch.Tensor>

In [65]:
loss =loss_fn(model(inputs) ,targets)
loss

tensor(2730.6150, grad_fn=<MseLossBackward0>)

## Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for "stochastic gradient descent". The term _stochastic_ indicates that samples are selected in random batches instead of as a single group.

In [66]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)
opt

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 1e-05
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

Note that `model.parameters()` is passed as an argument to `optim.SGD` so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate that controls the amount by which the parameters are modified.

## Train the model

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function `fit` that trains the model for a given number of epochs.

In [73]:
# Utility function to train the model

def fit(num_epochs , model,loss_fn ,opt ,train_dl):
  # Repeat for given number of epochs
  for epoch in range(num_epochs):

    # train with batches of data
    for xb ,yb in train_dl:
      #Generate predictions
      pred = model(xb)

      # Calculate loss
      loss = loss_fn(pred ,yb)
      # Compute Gradient
      loss.backward()
      # update parameters using gradient
      opt.step()
      # rest the gradient to zero
      opt.zero_grad()

      # Print progress
    if (epoch + 1) % 20 ==0 :
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch +1 ,num_epochs ,loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update and `opt.zero_grad` to reset the gradients to zero.

* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. `loss.item` returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [74]:
# let's train data for 100 epochs
fit(100 , model ,loss_fn ,opt ,train_dl)

Epoch [20/100], Loss: 1.4987
Epoch [40/100], Loss: 0.8149
Epoch [60/100], Loss: 1.1751
Epoch [80/100], Loss: 1.2360
Epoch [100/100], Loss: 1.6448


In [75]:
fit(200 ,model ,loss_fn ,opt ,train_dl)

Epoch [20/200], Loss: 0.6343
Epoch [40/200], Loss: 1.0385
Epoch [60/200], Loss: 0.9147
Epoch [80/200], Loss: 1.3657
Epoch [100/200], Loss: 0.7378
Epoch [120/200], Loss: 0.7820
Epoch [140/200], Loss: 1.5915
Epoch [160/200], Loss: 1.4460
Epoch [180/200], Loss: 1.3337
Epoch [200/200], Loss: 0.7870


In [76]:
fit(300 ,model ,loss_fn ,opt ,train_dl)

Epoch [20/300], Loss: 1.0003
Epoch [40/300], Loss: 0.8323
Epoch [60/300], Loss: 1.1439
Epoch [80/300], Loss: 0.5779
Epoch [100/300], Loss: 0.9406
Epoch [120/300], Loss: 0.7936
Epoch [140/300], Loss: 1.6306
Epoch [160/300], Loss: 0.6658
Epoch [180/300], Loss: 1.1604
Epoch [200/300], Loss: 1.0648
Epoch [220/300], Loss: 1.2260
Epoch [240/300], Loss: 1.1900
Epoch [260/300], Loss: 0.6816
Epoch [280/300], Loss: 1.1170
Epoch [300/300], Loss: 1.4463


In [77]:
preds = model(inputs)
preds

tensor([[ 56.9186,  70.3244],
        [ 81.9965, 100.5364],
        [118.3068, 132.8078],
        [ 20.8511,  37.7572],
        [101.7383, 118.4370],
        [ 55.6726,  69.2485],
        [ 81.8447, 100.6320],
        [118.5988, 133.4132],
        [ 22.0970,  38.8331],
        [102.8325, 119.6085],
        [ 56.7668,  70.4201],
        [ 80.7505,  99.4605],
        [118.4586, 132.7122],
        [ 19.7569,  36.5857],
        [102.9842, 119.5129]], grad_fn=<AddmmBackward0>)

In [78]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [79]:
model(torch.tensor([[75,63,44.]]))

tensor([[53.4300, 67.4755]], grad_fn=<AddmmBackward0>)